name: pipeline
channels:
  - defaults
  - conda-forge
  - r
dependencies:
  - python=3.7
  - pip
  - anaconda-client
  - conda-build
  - conda-verify
  - click
  - jinja2
  - joblib
  - jupyterlab
  - matplotlib
  - networkx
  - pandas
  - pre-commit
  - pyyaml
  - restructuredtext_lint
  - rpy2
  - sphinx
  - sphinx_rtd_theme
  - statsmodels
  - tqdm
  - pip:
    - stargazer
  - r-irkernel
  - r-stargazer
  - r-tidyverse
