name: pipeline
channels:
  - defaults
  - conda-forge
  - r
dependencies:
  - python=3.7
  - pip
  - anaconda-client
  - conda-build
  - conda-verify
  - click
  - jinja2
  - joblib
  - jupyterlab
  - matplotlib
  - networkx
  - numpydoc
  - pandas
  - pony
  - pre-commit
  - pydot
  - pytest
  - pytest-cov
  - pyyaml
  - restructuredtext_lint
  - rpy2
  - seaborn
  - sphinx
  - sphinx_rtd_theme
  - statsmodels
  - tqdm
  - pip:
    - bump2version
    - stargazer
  - r-feather
  - r-functional
  - r-irkernel
  - r-mass
  - r-stargazer
  - r-tidyverse
  - r-xtable
